databases:
  - name: task_management_production
    databaseName: task_management_production_0bz8
    user: task_management_production_0bz8_user

services:
  - type: web
    name: task_management_system
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_management_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
